### ISSUE TITLE
Double \\ issue

### ISSUE THREAD

**Issue by notaduck** [Evpok/latex-autocomplete#24] opened 2017-09-12 06:27 UTC
Hey. I have thiss weird issue with the package that if I type:
* (1)     \b  
* (2) Enter for autocompletion, and then I get
    \\begin{env}
  
    \end{env}  
  
What is up with the double back dashes? is this expected behavior?

**Comment by Evpok** [comment] 2017-09-12 11:03
Duplicate of #23

**Closed by Evpok** 2017-09-12 11:03 UTC
