### ISSUE TITLE
Environments not automatically ended

### ISSUE THREAD

**Issue by DavidPost-1** [Evpok/latex-autocomplete#2] opened 2016-01-11 20:37 UTC
In the demonstration gif hitting return after
*\begin{itemize}*

resulted in a corresponding
*\end{itemize}*

being automatically inserted. I am not seeing this behaviour by default.
I am on windows 8.1 using Atom version 1.3.3 and latex-autocomplete version 0.2.4.

**Comment by Evpok** [comment] 2016-01-27 14:32
Might have to do with

  - You begin on Windows (can't test it atm)
  - Your version of Atom

specifically, due to the way we attach to editors, we might not be attached on session restore after opening atom. If the problem persists, try closing and reopening the file, and if it works then, try updating atom, the bug was fixed in the latest stable iirc

**Comment by Evpok** [comment] 2016-04-07 22:58
I have made some changes that may have fixed the issue. Could you try to reproduce?

**Comment by Evpok** [comment] 2016-04-13 09:55
Closing for want of information. If the issue is still present, comment here and I'll reopen.

**Comment by Evpok** [comment] 2016-04-13 09:55
Closing for want of information. If the issue is still present, comment here and I'll reopen.

**Closed by Evpok** 2016-04-13 09:55 UTC
Labels: bug
