### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by IagobaApellaniz** [Evpok/latex-autocomplete#8] opened 2016-02-22 11:47 UTC
Mmmmm

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [latex-autocomplete](https://github.com/evpok/latex-autocomplete) package, v0.3.1

### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:810

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:790:15)
    at DisplayBuffer.module.exports.DisplayBuffer.screenRangeForBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:754:20)
    at TextEditorMarker.module.exports.TextEditorMarker.getScreenRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:141:33)
    at Cursor.module.exports.Cursor.moveUp (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:198:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1502:23
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1680:9)
    at TextEditor.module.exports.TextEditor.moveUp (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1501:19)
    at /Users/iagoba/.atom/packages/latex-autocomplete/lib/completer.js:32:33
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:671:27)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:572:12)
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:482:43)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:805:29
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:844:29
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1244:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:838:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2124:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2086:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:836:19)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:802:19)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditor.module.exports.TextEditor.insertNewline (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:817:19)
    at TextEditor.object.(anonymous function) [as insertNewline] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditor.commandRegistry.add.stopEventPropagationAndGroupUndo.editor:newline (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:522:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:576:34
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:805:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1244:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:575:22)
```

### Commands

```
  5x -3:56.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:39.1.0 latex-plus:compile (atom-text-editor.editor.is-focused)
  3x -2:53.1.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -2:52.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:45.4.0 latex-plus:compile (atom-text-editor.editor.is-focused)
     -2:24.5.0 editor:newline (atom-text-editor.editor.is-focused)
 12x -2:08.2.0 core:backspace (atom-text-editor.editor.is-focused)
  8x -1:40.6.0 core:move-left (atom-text-editor.editor.is-focused)
  7x -1:35.4.0 core:backspace (atom-text-editor.editor.is-focused)
  8x -1:22.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:14.7.0 latex-plus:compile (atom-text-editor.editor.is-focused)
  2x -0:31.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:07.5.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:06.9.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "latex",
      "latex-completions"
    ]
  }
}
```

### Installed Packages

```coffee
# User
bombe, v0.1.3
indent-detective, v0.1.0
ink, v0.3.2
julia-client, v0.3.1
language-latex, v0.6.1
latex-autocomplete, v0.3.1
latex-plus, v0.8.4
minimap, v4.19.0
pdf-view, v0.39.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by Evpok** [comment] 2016-02-22 14:56
Thanks for the report. What were you doing when it happened ?

**Comment by iagoba** [comment] 2016-02-23 22:58
I was just starting a new environment with `\begin{nameofenvironment}` and hitting enter rises the error message. 

Even if I restart Atom the error still reproduces wherever I hit enter on that context.

**Comment by Evpok** [comment] 2016-02-25 14:58
That's odd. Does it still happen if you close/reopen the file, or try in a different file ?

**Comment by Evpok** [comment] 2016-04-07 22:57
I have made some changes that may have fixed the issue. Could you try to reproduce?

**Comment by Evpok** [comment] 2016-04-13 09:56
Closing for want of information. If the issue is still present, comment here and I'll reopen.

**Closed by Evpok** 2016-04-13 09:56 UTC

**Comment by IagobaApellaniz** [comment] 2016-04-18 12:23
Now it works! I had the plug-in disabled since. It was annoying to be unable to hit enter after defining the first line of a new environment, `\begin{foo} [enter]` then CRASH. 

Thank you very much!
